export interface ProductSpec {
  label: string;
  value: string;
}

export interface Product {
  id: string;
  model: string;
  name: string;
  category: "simple" | "semi-auto" | "automated" | "special";
  categoryLabel: string;
  shortDescription: string;
  liftingCapacity: string;
  features: string[];
  specifications: ProductSpec[];
  safetySystem: string[];
  applicationScenarios: ProductSpec[];
}

export const productCategories = [
  {
    id: "simple",
    title: "Simple Parking Lifts",
    description: "Space-saving and durable parking solutions at low cost. Hydraulic-driven, easy to install and relocate.",
  },
  {
    id: "semi-auto",
    title: "Semi-Auto Parking Systems",
    description: "Intelligent semi-automated parking systems with smart controls. Ideal for residential and commercial spaces.",
  },
  {
    id: "automated",
    title: "Fully Automated Systems",
    description: "High-tech fully automated parking towers and rotary systems for maximum space efficiency.",
  },
  {
    id: "special",
    title: "Special Platforms",
    description: "Vehicle transport systems and turntables for specialized applications.",
  },
];

export const products: Product[] = [
  // ─── SIMPLE PARKING LIFTS ───
  {
    id: "tp-320",
    model: "TP-320",
    name: "Four Post Car Parking Lift",
    category: "simple",
    categoryLabel: "Simple Parking Lift",
    shortDescription: "Heavy-duty four post hydraulic lift with 3,200 KG capacity. Ideal for sedans and SUVs.",
    liftingCapacity: "3,200 KG",
    features: [
      "Double Hydraulic Lifting Cylinders Direct Drive",
      "Multiple Parking Heights",
      "100% Laser Cutting Process for All Parts",
      "Preassembled Parts for Easy Installation",
      "Effortless Disassembly and Relocation",
      "Safety Key Switch Controller",
      "Hydraulic Overload Protection",
      "Anti-Skid Ramp and Platform",
      "Anti-Rust Smooth Powder Coating Finishing",
      "Enhanced Anti-Corrosion Galvanized Waving Plates",
      "Tire Protection Plates",
      "IP65 Electrical Devices for Outdoor Use",
      "12-Month Warranty (Extended Available)",
      "Customizable Colors",
      "Optional Remote Control",
      "Posts Can Be Shared for Multiple Parallel Lifts",
    ],
    specifications: [
      { label: "Model", value: "TP-320" },
      { label: "Lifting Capacity", value: "3,200 KG" },
      { label: "Vehicle Height", value: "1,550–2,050 mm" },
      { label: "Vehicle Width", value: "≤ 2,200 mm" },
      { label: "Vehicle Length", value: "5,000 mm" },
      { label: "Control Box", value: "Integrated Modules for Simple Wiring" },
      { label: "Power Unit", value: "3.0 KW Hydraulic" },
      { label: "Electrical Requirements", value: "Customizable: 3-Phase, 50/60 Hz" },
      { label: "Control Power", value: "24V" },
      { label: "Parking Time", value: "45–55 Seconds" },
    ],
    safetySystem: ["17 Full Range Anti-Fall Locks", "Limit Switches", "Emergency Stop Button"],
    applicationScenarios: [
      { label: "Vehicle Model", value: "Sedan, Regular SUV" },
      { label: "Foundation", value: "C25–C30; thickness: 300 mm" },
      { label: "Ceiling Height", value: "3,900 mm (Sedan+SUV) / 4,300 mm (2 SUVs)" },
      { label: "Environment", value: "Indoor/Outdoor (protection devices available)" },
    ],
  },
  {
    id: "tp-270",
    model: "TP-270",
    name: "Two Post Car Parking Lift",
    category: "simple",
    categoryLabel: "Simple Parking Lift",
    shortDescription: "Versatile two post lift with 2,700 KG capacity. Supports 1-phase or 3-phase power.",
    liftingCapacity: "2,700 KG",
    features: [
      "Double Hydraulic Lifting Cylinders Direct Drive",
      "Multiple Parking Heights",
      "100% Laser Cutting Process for All Parts",
      "Preassembled Parts for Easy Installation",
      "Effortless Disassembly and Relocation",
      "Safety Key Switch Controller",
      "Hydraulic Overload Protection",
      "Anti-Skid Ramp and Platform",
      "Anti-Rust Smooth Powder Coating Finishing",
      "Enhanced Anti-Corrosion Galvanized Waving Plates",
      "Optional Remote Control",
      "Customizable Colors",
      "12-Month Warranty (Extended Available)",
      "Posts Can Be Shared for Multiple Parallel Lifts",
    ],
    specifications: [
      { label: "Model", value: "TP-270" },
      { label: "Lifting Capacity", value: "2,700 KG" },
      { label: "Vehicle Height", value: "1,550–2,050 mm" },
      { label: "Vehicle Width", value: "2,200 mm" },
      { label: "Vehicle Length", value: "5,000 mm" },
      { label: "Control Box", value: "Integrated Modules for Simple Wiring" },
      { label: "Power Unit", value: "2.2 KW Hydraulic" },
      { label: "Electrical Requirements", value: "Customizable: 1-Phase or 3-Phase" },
      { label: "Control Power", value: "24V" },
      { label: "Parking Time", value: "45–55 Seconds" },
    ],
    safetySystem: ["17 Full Range Anti-Fall Locks", "Limit Switches", "Emergency Stop Button", "Photocell Sensor", "Lock Down Button"],
    applicationScenarios: [
      { label: "Vehicle Model", value: "Sedan, Regular SUV" },
      { label: "Foundation", value: "C25–C30; thickness: 300 mm" },
      { label: "Ceiling Height", value: "3,900 mm (Sedan+SUV) / 4,300 mm (2 SUVs)" },
      { label: "Buildings", value: "Private Garage, Residential, Shopping Mall, Car Dealership" },
      { label: "Environment", value: "Indoor/Outdoor (protection devices available)" },
    ],
  },
  {
    id: "tp-270h",
    model: "TP-270H",
    name: "Two Post Car Parking Lift",
    category: "simple",
    categoryLabel: "Simple Parking Lift",
    shortDescription: "Single hydraulic cylinder two post lift with 2,700 KG capacity. Compact and efficient.",
    liftingCapacity: "2,700 KG",
    features: [
      "Single Hydraulic Lifting Cylinder Direct Drive",
      "Multiple Parking Heights",
      "100% Laser Cutting Process for All Parts",
      "Preassembled Parts for Easy Installation",
      "Effortless Disassembly and Relocation",
      "Safety Key Switch Controller",
      "Hydraulic Overload Protection",
      "Anti-Skid Ramp and Platform",
      "Anti-Rust Smooth Powder Coating Finishing",
      "Enhanced Anti-Corrosion Galvanized Waving Plates",
      "Optional Remote Control",
      "Customizable Colors",
      "12-Month Warranty (Extended Available)",
      "Posts Can Be Shared for Multiple Parallel Lifts",
    ],
    specifications: [
      { label: "Model", value: "TP-270H" },
      { label: "Lifting Capacity", value: "2,700 KG" },
      { label: "Vehicle Height", value: "1,550–2,050 mm" },
      { label: "Vehicle Width", value: "< 2,050 mm" },
      { label: "Vehicle Length", value: "5,000 mm" },
      { label: "Control Box", value: "Integrated Modules for Simple Wiring" },
      { label: "Power Unit", value: "2.2 KW Hydraulic" },
      { label: "Electrical Requirements", value: "Customizable: 1-Phase or 3-Phase, 50/60 Hz" },
      { label: "Control Power", value: "24V" },
      { label: "Parking Time", value: "45–55 Seconds" },
    ],
    safetySystem: ["17 Full Range Anti-Fall Locks", "Limit Switches", "Emergency Stop Button", "Photocell Sensor", "Lock Down Button"],
    applicationScenarios: [
      { label: "Vehicle Model", value: "Sedan, Regular SUV" },
      { label: "Foundation", value: "C25–C30; thickness: 300 mm" },
      { label: "Ceiling Height", value: "3,900 mm (Sedan+SUV) / 4,300 mm (2 SUVs)" },
      { label: "Buildings", value: "Private Garage, Residential, Shopping Mall, Car Dealership" },
      { label: "Environment", value: "Indoor/Outdoor (protection devices available)" },
    ],
  },
  {
    id: "tp-230h",
    model: "TP-230H",
    name: "Two Post Car Parking Lift",
    category: "simple",
    categoryLabel: "Simple Parking Lift",
    shortDescription: "Compact two post lift with 2,300 KG capacity. Faster lifting speed than standard 2-post lifts.",
    liftingCapacity: "2,300 KG",
    features: [
      "Single Hydraulic Lifting Cylinder Direct Drive",
      "Multiple Parking Heights",
      "Faster Lifting Speed Than Other 2-Post Lifts",
      "100% Laser Cutting Process for All Parts",
      "Preassembled Parts for Easy Installation",
      "Effortless Disassembly and Relocation",
      "Safety Key Switch Controller",
      "Hydraulic Overload Protection",
      "Anti-Skid Ramp and Platform",
      "Anti-Rust Smooth Powder Coating Finishing",
      "Enhanced Anti-Corrosion Galvanized Waving Plates",
      "Optional Remote Control",
      "Customizable Colors",
      "12-Month Warranty (Extended Available)",
      "Posts Can Be Shared for Multiple Parallel Lifts",
    ],
    specifications: [
      { label: "Model", value: "TP-230H" },
      { label: "Lifting Capacity", value: "2,300 KG" },
      { label: "Vehicle Height", value: "1,550–2,050 mm" },
      { label: "Vehicle Width", value: "≤ 2,050 mm" },
      { label: "Vehicle Length", value: "5,000 mm" },
      { label: "Control Box", value: "Integrated Modules for Simple Wiring" },
      { label: "Power Unit", value: "2.2 KW Hydraulic" },
      { label: "Electrical Requirements", value: "Customizable: 1-Phase or 3-Phase, 50/60 Hz" },
      { label: "Control Power", value: "24V" },
      { label: "Parking Time", value: "45–55 Seconds" },
    ],
    safetySystem: ["17 Full Range Anti-Fall Locks", "Limit Switches", "Emergency Stop Button", "Photocell Sensor", "Lock Down Button"],
    applicationScenarios: [
      { label: "Vehicle Model", value: "Sedan, Regular SUV" },
      { label: "Foundation", value: "C25–C30; thickness: ≥ 300 mm" },
      { label: "Ceiling Height", value: "3,900 mm (Sedan+SUV) / 4,300 mm (2 SUVs)" },
      { label: "Buildings", value: "Private Garage, Residential, Shopping Mall, Car Dealership" },
      { label: "Environment", value: "Indoor/Outdoor (protection devices available)" },
    ],
  },
  {
    id: "tp-200",
    model: "TP-200",
    name: "Two Post Car Parking Lift",
    category: "simple",
    categoryLabel: "Simple Parking Lift",
    shortDescription: "Low-profile two post lift with 2,000 KG capacity. Suitable for low ceiling and narrow spaces.",
    liftingCapacity: "2,000 KG",
    features: [
      "Double Hydraulic Lifting Cylinders Direct Drive",
      "Suitable for Low Ceiling Height and Narrow Space",
      "100% Laser Cutting Process for All Parts",
      "Preassembled Parts for Easy Installation",
      "Effortless Disassembly and Relocation",
      "Safety Key Switch Controller",
      "Hydraulic Overload Protection",
      "Anti-Skid Ramp and Platform",
      "Optional Remote Control",
      "Customizable Colors",
      "12-Month Warranty (Extended Available)",
    ],
    specifications: [
      { label: "Model", value: "TP-200" },
      { label: "Lifting Capacity", value: "2,000 KG" },
      { label: "Vehicle Height", value: "1,550–1,850 mm" },
      { label: "Vehicle Width", value: "1,850 mm" },
      { label: "Vehicle Length", value: "5,000 mm" },
      { label: "Control Box", value: "Integrated Modules for Simple Wiring" },
      { label: "Power Unit", value: "2.2 KW Hydraulic" },
      { label: "Electrical Requirements", value: "Customizable: 1-Phase or 3-Phase, 50/60 Hz" },
      { label: "Control Power", value: "24V" },
      { label: "Parking Time", value: "45–55 Seconds" },
    ],
    safetySystem: ["Anti-Fall Hooks", "Limit Switches", "Emergency Stop Button", "Photocell Sensor"],
    applicationScenarios: [
      { label: "Vehicle Model", value: "Sedan" },
      { label: "Foundation", value: "C25–C30" },
      { label: "Ceiling Height", value: "2,900 mm" },
      { label: "Buildings", value: "Private Garage, Residential, Shopping Mall, Car Dealership" },
      { label: "Environment", value: "Indoor" },
    ],
  },
  {
    id: "tts-3",
    model: "TTS-3",
    name: "Two Post Car Parking Lift",
    category: "simple",
    categoryLabel: "Simple Parking Lift",
    shortDescription: "Triple-stacker two post lift with 2,500 KG capacity. Parks 3 vehicles vertically.",
    liftingCapacity: "2,500 KG",
    features: [
      "Double Hydraulic Lifting Cylinders Direct Drive",
      "Multiple Parking Heights",
      "100% Laser Cutting Process for All Parts",
      "Preassembled Parts for Easy Installation",
      "Effortless Disassembly and Relocation",
      "Press Button Operation Box",
      "Hydraulic Overload Protection",
      "Enhanced Anti-Corrosion Galvanized Waving Plates",
      "Optional Remote Control",
      "12-Month Warranty (Extended Available)",
    ],
    specifications: [
      { label: "Model", value: "TTS-3" },
      { label: "Lifting Capacity", value: "2,500 KG" },
      { label: "Vehicle Height", value: "1,550–1,950 mm" },
      { label: "Vehicle Width", value: "≤ 2,100 mm" },
      { label: "Vehicle Length", value: "5,000 mm" },
      { label: "Control Box", value: "Integrated Modules for Simple Wiring" },
      { label: "Power Unit", value: "3 KW Hydraulic" },
      { label: "Electrical Requirements", value: "Customizable: 1-Phase or 3-Phase, 50/60 Hz" },
      { label: "Control Power", value: "24V" },
      { label: "Lifting Speed", value: "3 m/min" },
    ],
    safetySystem: ["Anti-Fall Locks", "Limit Switches", "Emergency Stop Button", "Lock Down Button", "Photocell Sensor"],
    applicationScenarios: [
      { label: "Vehicle Model", value: "Sedan or Small SUV" },
      { label: "Foundation", value: "C25–C30; thickness: > 300 mm" },
      { label: "Ceiling Height", value: "5,900 mm" },
      { label: "Buildings", value: "Private Garage, Residential, Shopping Mall, Car Dealer" },
      { label: "Environment", value: "Indoor/Outdoor (protection devices available)" },
    ],
  },
  {
    id: "fp-360",
    model: "FP-360",
    name: "Scissor Car Parking Lift",
    category: "simple",
    categoryLabel: "Simple Parking Lift",
    shortDescription: "Scissor-type lift with 3,600 KG capacity. Supports sedans, SUVs and pick-up trucks.",
    liftingCapacity: "3,600 KG",
    features: [
      "Single Hydraulic Lifting Cylinder Direct Drive",
      "Multiple Parking Heights",
      "100% Laser Cutting Process for All Parts",
      "Preassembled Parts for Easy Installation and Relocation",
      "Safety Key Switch Controller",
      "Hydraulic Overload Protection",
      "Anti-Skid Ramp and Platform",
      "Anti-Rust Smooth Powder Coating Finishing",
      "Enhanced Anti-Corrosion Galvanized Waving Plates",
      "Optional: Remote Control, Middle Cover Plate, Tire Protection Side Beam Plate",
      "Customizable Colors",
      "Lock Release: Manual/Electrical",
    ],
    specifications: [
      { label: "Model", value: "FP-360" },
      { label: "Lifting Capacity", value: "3,600 KG" },
      { label: "Vehicle Height", value: "1,550–2,050 mm" },
      { label: "Vehicle Width", value: "≤ 2,050 mm" },
      { label: "Vehicle Length", value: "5,000 mm" },
      { label: "Control Box", value: "Integrated Modules for Simple Wiring" },
      { label: "Power Unit", value: "2.2 KW Hydraulic" },
      { label: "Electrical Requirements", value: "Customizable: 1-Phase or 3-Phase, 50/60 Hz" },
      { label: "Control Power", value: "24V" },
      { label: "Parking Time", value: "40 Seconds" },
    ],
    safetySystem: ["12 Full Range Anti-Fall Locks", "Limit Switches", "Emergency Stop Button", "Anti-Loosening Locks"],
    applicationScenarios: [
      { label: "Vehicle Model", value: "Sedan, SUV, Regular Pick-up Truck" },
      { label: "Foundation", value: "C25–C30; thickness: ≥ 300 mm" },
      { label: "Ceiling Height", value: "3,600 mm" },
      { label: "Buildings", value: "Garage, Parking Lot, Car Repairing" },
      { label: "Environment", value: "Indoor/Outdoor (protection devices available)" },
    ],
  },
  {
    id: "fp-360d",
    model: "FP-360D",
    name: "Four Post Double Car Parking Lift",
    category: "simple",
    categoryLabel: "Simple Parking Lift",
    shortDescription: "Double-deck four post lift. Parks 4 cars simultaneously with 4,000 KG total capacity.",
    liftingCapacity: "4,000 KG",
    features: [
      "Single Hydraulic Lifting Cylinder Direct Drive",
      "Multiple Parking Heights",
      "100% Laser Cutting Process for All Parts",
      "Preassembled Parts for Easy Installation and Relocation",
      "Safety Key Switch Controller",
      "Hydraulic Overload Protection",
      "Enhanced Anti-Corrosion Galvanized Waving Plates",
      "Optional: Remote Control, Middle Cover",
      "Customizable Colors",
      "Lock Release: Electrical",
      "Four Cars Parked at the Same Time",
      "12-Month Warranty (Extended Available)",
    ],
    specifications: [
      { label: "Model", value: "FP-360D" },
      { label: "Lifting Capacity", value: "4,000 KG (2,000 KG per vehicle)" },
      { label: "Vehicle Height", value: "1,550–1,950 mm" },
      { label: "Vehicle Width", value: "1,850 mm" },
      { label: "Vehicle Length", value: "5,000 mm" },
      { label: "Control Box", value: "Integrated Modules for Simple Wiring" },
      { label: "Power Unit", value: "2.2 KW Hydraulic" },
      { label: "Electrical Requirements", value: "Customizable: 2-Phase or 3-Phase, 50/60 Hz" },
      { label: "Control Power", value: "24V" },
      { label: "Parking Time", value: "40 Seconds" },
    ],
    safetySystem: ["Full Range Anti-Fall Locks", "Limit Switches", "Emergency Stop Button", "Anti-Loosening Locks"],
    applicationScenarios: [
      { label: "Vehicle Model", value: "Sedan" },
      { label: "Foundation", value: "C25–C30; thickness: ≥ 200 mm" },
      { label: "Ceiling Height", value: "3,800 mm" },
      { label: "Buildings", value: "Garage, Parking Lot, Car Repairing" },
      { label: "Environment", value: "Indoor/Outdoor (protection devices available)" },
    ],
  },
  {
    id: "fp-360x",
    model: "FP-360X",
    name: "Triple Scissor Car Parking Lift",
    category: "simple",
    categoryLabel: "Simple Parking Lift",
    shortDescription: "Triple-level scissor lift parking 3 vehicles at once. 2,500 KG upper, 2,300 KG mid capacity.",
    liftingCapacity: "2,500 KG (upper) / 2,300 KG (mid)",
    features: [
      "Single Hydraulic Lifting Cylinder Direct Drive",
      "Multiple Parking Heights",
      "100% Laser Cutting Process for All Parts",
      "Preassembled Parts for Easy Installation and Relocation",
      "Safety Key Switch Controller",
      "Hydraulic Overload Protection",
      "Enhanced Anti-Corrosion Galvanized Waving Plates",
      "Optional: Remote Control, Middle Cover Plate",
      "Customizable Colors",
      "Lock Release: Manual/Electrical",
      "Three Vehicles Parked at the Same Time",
      "12-Month Warranty (Extended Available)",
    ],
    specifications: [
      { label: "Model", value: "FP-360X" },
      { label: "Lifting Capacity", value: "2,500 KG (upper); 2,300 KG (mid)" },
      { label: "Vehicle Height", value: "1,550–2,050 mm" },
      { label: "Vehicle Width", value: "< 2,000 mm" },
      { label: "Vehicle Length", value: "5,000 mm" },
      { label: "Control Box", value: "Integrated Modules for Simple Wiring" },
      { label: "Power Unit", value: "3.0 KW Hydraulic" },
      { label: "Electrical Requirements", value: "Customizable: 3-Phase, 50/60 Hz" },
      { label: "Control Power", value: "24V" },
      { label: "Parking Time", value: "55 Seconds" },
    ],
    safetySystem: ["Full Range Anti-Fall Locks", "Limit Switches", "Emergency Stop Button", "Anti-Loosening Locks"],
    applicationScenarios: [
      { label: "Vehicle Model", value: "Sedan, Regular SUV" },
      { label: "Foundation", value: "C25–C30; thickness: 300 mm" },
      { label: "Ceiling Height", value: "5,500 mm" },
      { label: "Buildings", value: "Garage, Parking Lot, Car Repairing, Car Dealer, Shopping Mall" },
      { label: "Environment", value: "Indoor/Outdoor (protection devices available)" },
    ],
  },
  {
    id: "fp-630",
    model: "FP-630",
    name: "Four Post Car Parking Lift",
    category: "simple",
    categoryLabel: "Simple Parking Lift",
    shortDescription: "Heavy-duty four post lift with dual capacity. 2,700 KG upper and 3,600 KG middle levels.",
    liftingCapacity: "2,700 KG (upper) / 3,600 KG (mid)",
    features: [
      "Single Hydraulic Lifting Cylinder Direct Drive",
      "Multiple Parking Heights",
      "100% Laser Cutting Process for All Parts",
      "Preassembled Parts for Easy Installation and Relocation",
      "Press Button Operation Box",
      "Hydraulic Overload Protection",
      "Anti-Skid Ramp and Platform",
      "Anti-Rust Smooth Powder Coating Finishing",
      "Enhanced Anti-Corrosion Galvanized Waving Plates",
      "Optional: Remote Control, Middle Cover Plate, Oil Drip Tray, Tire Protection Plate",
      "Customizable Colors",
      "Suitable for Auto Repair Shops",
      "Lock Release: Manual/Electrical",
      "Flexibility: Easy to Separate into Two Individual Lifts",
      "12-Month Warranty (Extended Available)",
    ],
    specifications: [
      { label: "Model", value: "FP-630" },
      { label: "Lifting Capacity", value: "2,700 KG (upper); 3,600 KG (middle)" },
      { label: "Vehicle Height", value: "1,550–2,050 mm" },
      { label: "Vehicle Width", value: "< 2,000 mm" },
      { label: "Vehicle Length", value: "5,400 mm" },
      { label: "Control Box", value: "Integrated Modules for Simple Wiring" },
      { label: "Power Unit", value: "2.2 KW Hydraulic" },
      { label: "Electrical Requirements", value: "Customizable: 1-Phase or 3-Phase, 50/60 Hz" },
      { label: "Control Power", value: "24V" },
      { label: "Parking Time", value: "50 Seconds" },
    ],
    safetySystem: ["Full Range Anti-Fall Locks", "Limit Switches", "Emergency Stop Button", "Anti-Loosening Locks"],
    applicationScenarios: [
      { label: "Vehicle Model", value: "Sedan, SUV, Regular Pick-up Truck" },
      { label: "Foundation", value: "C25–C30; thickness: 300 mm" },
      { label: "Ceiling Height", value: "5,600 mm" },
      { label: "Buildings", value: "Garage, Parking Lot, Car Repairing, Car Dealer, Shopping Mall" },
      { label: "Environment", value: "Indoor/Outdoor (protection devices available)" },
    ],
  },
  {
    id: "mps",
    model: "MPS-3/4/5",
    name: "Multi-Stacker Car Parking Lift",
    category: "simple",
    categoryLabel: "Simple Parking Lift",
    shortDescription: "Multi-level stacker lift for 3–5 vehicles. Ideal for car storage and dealerships.",
    liftingCapacity: "2,000–2,500 KG",
    features: [
      "Single Hydraulic Lifting Cylinder Direct Drive Design",
      "100% Laser Cutting Process for All Parts",
      "Preassembled Parts for Easy Installation",
      "Effortless Disassembly and Relocation",
      "Press Button Operation Box",
      "Hydraulic Overload Protection",
      "Anti-Skid Ramp and Platform",
      "Anti-Rust Smooth Powder Coating Finishing",
      "Optional Remote Control",
      "Customizable Colors and Level Number",
      "Suitable for Car Storage",
      "Enhanced Parking Platforms with Anti-Fall Design on Each Corner",
      "Power Station and Post Can Be Shared",
      "12-Month Warranty (Extended Available)",
    ],
    specifications: [
      { label: "Model", value: "MPS-3/4/5" },
      { label: "Lifting Capacity", value: "2,000–2,500 KG" },
      { label: "Vehicle Height", value: "1,550–2,050 mm" },
      { label: "Vehicle Width", value: "2,300 mm" },
      { label: "Vehicle Length", value: "5,500 mm" },
      { label: "Control Box", value: "Integrated Modules for Simple Wiring" },
      { label: "Power Unit", value: "5.5–7.5 KW Hydraulic" },
      { label: "Electrical Requirements", value: "50/60 Hz" },
      { label: "Control Power", value: "24V" },
      { label: "Parking Time", value: "50 Seconds" },
    ],
    safetySystem: [
      "Wire Rope Anti-Fall Position System",
      "Alarm Light",
      "Side Stop Plate",
      "Front Cover Plate",
      "Position Locks",
      "Limit Switches",
      "Emergency Stop Button",
    ],
    applicationScenarios: [
      { label: "Vehicle Model", value: "Sedan and SUV" },
      { label: "Foundation", value: "C25–C30; thickness: > 300 mm" },
      { label: "Ceiling Height", value: "6,000 / 7,800 / 9,650 mm" },
      { label: "Buildings", value: "Private Garage, Car Dealership" },
      { label: "Environment", value: "Indoor/Outdoor (protection devices available)" },
    ],
  },

  // ─── SEMI-AUTO PARKING SYSTEMS ───
  {
    id: "ips",
    model: "IPS-2/3/4",
    name: "In-ground Parking System",
    category: "semi-auto",
    categoryLabel: "Semi-Auto Parking System",
    shortDescription: "Underground parking system that hides vehicles below ground level. Perfect for private villas.",
    liftingCapacity: "2,000–2,500 KG",
    features: [
      "Hydraulic Driven with Precise Control",
      "Vehicles Hidden Underground When Parked",
      "100% Laser Cutting Process for All Parts",
      "Preassembled Parts for Easy Installation",
      "Safety Key Switch Controller",
      "Hydraulic Overload Protection",
      "Anti-Skid Platform",
      "Galvanized Waving Plates with Powder Coating",
      "Customizable Colors",
      "12-Month Warranty (Extended Available)",
    ],
    specifications: [
      { label: "Model", value: "IPS-2/3/4" },
      { label: "Lifting Capacity", value: "2,000–2,500 KG" },
      { label: "Vehicle Height", value: "1,550–2,050 mm" },
      { label: "Vehicle Width", value: "≤ 2,050 mm" },
      { label: "Vehicle Length", value: "5,000 mm" },
      { label: "Control Box", value: "PLC Control" },
      { label: "Power Unit", value: "5.5 KW Hydraulic" },
      { label: "Electrical Requirements", value: "Customizable: 3-Phase, 50/60 Hz" },
      { label: "Control Power", value: "24V" },
      { label: "Lifting Speed", value: "3.6–8.0 m/min" },
    ],
    safetySystem: ["Full Range Anti-Fall Locks", "Limit Switches", "Emergency Stop Button", "Photocell Sensors"],
    applicationScenarios: [
      { label: "Vehicle Model", value: "Sedan (SUV customizable)" },
      { label: "Pit Depth", value: "2,430 mm" },
      { label: "Buildings", value: "Private Villa, Apartment" },
      { label: "Environment", value: "Indoor/Outdoor (protection devices available)" },
    ],
  },
  {
    id: "ptp-2",
    model: "PTP-2",
    name: "Pit Parking System",
    category: "semi-auto",
    categoryLabel: "Semi-Auto Parking System",
    shortDescription: "Pit-type parking system with 2,500 KG capacity. Ideal for private villas and apartments.",
    liftingCapacity: "2,500 KG",
    features: [
      "Hydraulic Driven with Precise Control",
      "100% Laser Cutting Process for All Parts",
      "Preassembled Parts for Easy Installation",
      "Safety Key Switch Controller",
      "Hydraulic Overload Protection",
      "Anti-Skid Platform",
      "Galvanized Waving Plates with Powder Coating",
      "Customizable Colors",
      "12-Month Warranty (Extended Available)",
    ],
    specifications: [
      { label: "Model", value: "PTP-2" },
      { label: "Lifting Capacity", value: "2,500 KG" },
      { label: "Vehicle Height", value: "1,550–2,050 mm" },
      { label: "Vehicle Width", value: "1,850 mm" },
      { label: "Vehicle Length", value: "5,000 mm" },
      { label: "Control Box", value: "Integrated Modules for Simple Wiring" },
      { label: "Power Unit", value: "2.2/4/5.5/7.5 KW Hydraulic" },
      { label: "Electrical Requirements", value: "Customizable: 1-Phase or 3-Phase, 50/60 Hz" },
      { label: "Control Power", value: "24V" },
      { label: "Parking Time", value: "50 Seconds" },
    ],
    safetySystem: [
      "16 Full Range Anti-Fall Locks",
      "Anti-Fall Ladders",
      "Limit Switches",
      "Emergency Stop Button",
      "Anti-Burst Valves",
      "Photocell Sensor",
      "Pressure Relief Lock Valve",
    ],
    applicationScenarios: [
      { label: "Vehicle Model", value: "Sedan, Regular SUV" },
      { label: "Pit Depth", value: "≥ 2,000 mm" },
      { label: "Buildings", value: "Private Villa, Apartment" },
      { label: "Environment", value: "Indoor/Outdoor (protection devices available)" },
    ],
  },
  {
    id: "cps-2",
    model: "CPS-2",
    name: "Cantilever Car Parking System",
    category: "semi-auto",
    categoryLabel: "Semi-Auto Parking System",
    shortDescription: "Wall-mounted cantilever parking system with 2,000 KG capacity. Requires load-bearing wall.",
    liftingCapacity: "2,000 KG",
    features: [
      "Double Hydraulic Lifting Cylinders Direct Drive",
      "100% Laser Cutting Process for All Parts",
      "Safety Key Switch Controller",
      "Hydraulic Overload Protection",
      "Anti-Skid Ramp and Platform",
      "Galvanized Waving Plates and Powder Coating Finishing",
      "Optional Remote Control",
      "Customizable Colors",
      "12-Month Warranty (Extended Available)",
      "Free-Access Parking Platform",
    ],
    specifications: [
      { label: "Model", value: "CPS-2" },
      { label: "Lifting Capacity", value: "2,000 KG" },
      { label: "Vehicle Height", value: "1,550–2,050 mm" },
      { label: "Vehicle Width", value: "1,850 mm" },
      { label: "Vehicle Length", value: "5,000 mm" },
      { label: "Control Box", value: "Integrated Modules for Simple Wiring" },
      { label: "Power Unit", value: "2.2 KW Hydraulic" },
      { label: "Electrical Requirements", value: "Customizable: 1-Phase or 3-Phase, 50/60 Hz" },
      { label: "Control Power", value: "24V" },
    ],
    safetySystem: ["Full Range Anti-Fall Locks", "Limit Switches", "Emergency Stop Button", "Optional Anti-Explosion Valve"],
    applicationScenarios: [
      { label: "Vehicle Model", value: "Sedan" },
      { label: "Pit Depth", value: "2,100 mm" },
      { label: "Buildings", value: "Private Villa, Apartment" },
      { label: "Note", value: "Back wall must be load-bearing. Ceiling must bear load." },
      { label: "Environment", value: "Indoor/Outdoor (protection devices available)" },
    ],
  },
  {
    id: "pps",
    model: "PPS-2~PPS-6",
    name: "Lift-Sliding Puzzle Parking System",
    category: "semi-auto",
    categoryLabel: "Semi-Auto Parking System",
    shortDescription: "Multi-level puzzle parking with lift and slide mechanism. Maximizes parking capacity.",
    liftingCapacity: "2,000–2,500 KG",
    features: [
      "Motor or Hydraulic Driven",
      "Intelligent Smart Parking System",
      "100% Laser Cutting Process for All Parts",
      "Swiping IC Card / Press Button Operation",
      "Hydraulic Overload Protection",
      "Anti-Skid Ramp and Platform",
      "Galvanized Waving Plates or Powder Coating",
      "Customizable Colors and Level Numbers",
      "Free-Access Parking Platform",
      "Schneider PLC Controller",
      "Low Noise Operation",
      "12-Month Warranty (Extended Available)",
    ],
    specifications: [
      { label: "Model", value: "PPS-2 ~ PPS-6" },
      { label: "Lifting Capacity", value: "2,000–2,500 KG (on floor)" },
      { label: "Vehicle Height", value: "1,550–2,050 mm" },
      { label: "Vehicle Width", value: "2,050 mm" },
      { label: "Vehicle Length", value: "< 5,300 mm" },
      { label: "Control Box", value: "PLC Control" },
      { label: "Sliding Motor", value: "0.2/0.4 kW" },
      { label: "Lifting Motor", value: "22–37 kW" },
      { label: "Lifting Speed", value: "4–6 m/min" },
      { label: "Sliding Speed", value: "6–8 m/min" },
      { label: "Operation Mode", value: "Button with IC Card" },
    ],
    safetySystem: [
      "Anti-Fall Hooks",
      "Limit Switches",
      "Emergency Stop Button",
      "Photocell Sensors",
      "Anti-Loose Device",
      "Stop Rod for Tire Protection",
      "Optional Safety Gate on Ground Floor",
    ],
    applicationScenarios: [
      { label: "Vehicle Model", value: "Sedan / SUV" },
      { label: "Ceiling Height", value: "Customizable" },
      { label: "Buildings", value: "Residential Community, Shopping Mall, Office Building" },
      { label: "Environment", value: "Indoor/Outdoor" },
    ],
  },
  {
    id: "rps",
    model: "RPS",
    name: "Rotary Parking System",
    category: "semi-auto",
    categoryLabel: "Semi-Auto Parking System",
    shortDescription: "Eye-catching rotary design parking 8–20 vehicles in minimal footprint. Fully automated operation.",
    liftingCapacity: "2,000–2,500 KG",
    features: [
      "Minimum 8, Maximum 20 Parking Spaces",
      "Eye-Catching Innovative Design",
      "100% Laser Cutting Process for All Parts",
      "Preassembled Parts for Easy Installation",
      "IC Card / Touch Screen Operation",
      "Anti-Skid Ramp and Platform",
      "Anti-Rust Smooth Powder Coating",
      "Customizable Colors",
      "Fully Automated Operation",
      "Extremely Low Noise",
      "Low Electrical Power Consumption",
      "Motor: SEW or Nord",
      "Easy Maintenance",
      "12-Month Warranty (Extended Available)",
    ],
    specifications: [
      { label: "Model", value: "RPS" },
      { label: "Lifting Capacity", value: "2,000–2,500 KG" },
      { label: "Vehicle Height", value: "1,550–2,050 mm" },
      { label: "Vehicle Width", value: "1,900 mm" },
      { label: "Vehicle Length", value: "≤ 5,300 mm" },
      { label: "Control Box", value: "PLC Control" },
      { label: "Power Unit", value: "9.2 kW × 2" },
      { label: "Electrical Requirements", value: "Customizable: 3-Phase, 50/60 Hz" },
      { label: "Control Power", value: "24V" },
      { label: "Lifting Speed", value: "4–6 m/min" },
    ],
    safetySystem: ["Limit Switches", "Emergency Stop Button", "Photocell Sensors", "Mechanical Interlock"],
    applicationScenarios: [
      { label: "Vehicle Model", value: "Sedan / SUV" },
      { label: "Ceiling Height", value: "Customizable" },
      { label: "Site", value: "Limited Parking Area" },
      { label: "Environment", value: "Indoor/Outdoor (protection devices available)" },
    ],
  },

  // ─── FULLY AUTOMATED SYSTEMS ───
  {
    id: "atp",
    model: "ATP",
    name: "Automated Tower Parking System",
    category: "automated",
    categoryLabel: "Fully Automated System",
    shortDescription: "The most cost-effective fully automated parking tower. Maximum space utilization with smart PLC control.",
    liftingCapacity: "2,000 KG",
    features: [
      "Advanced PLC Control System (Schneider)",
      "Smooth Operation and High Efficiency",
      "Human-Machine Computer Integrated Management",
      "Maximized Space Utilization",
      "Fully Automated Parking Process",
      "Easy Operation and Maintenance",
      "Customizable Appearance",
      "SEW Brand Motor for Strong Power",
      "Energy Saving",
      "Low Noise",
      "Oil Drip Tray Platform",
      "Vehicle Guidance System",
    ],
    specifications: [
      { label: "Model", value: "ATP" },
      { label: "Lifting Capacity", value: "2,000 KG (max 2,050 KG)" },
      { label: "Vehicle Dimension", value: "L5,200 × W2,050 × H2,050 mm" },
      { label: "Control Box", value: "PLC Control" },
      { label: "Sliding Motor", value: "1.5/11 kW" },
      { label: "Lifting Motor", value: "0.2/2.2/3.7 kW" },
      { label: "Electrical Requirements", value: "Customizable: 3-Phase, 50/60 Hz" },
      { label: "Control Power", value: "240V" },
      { label: "Parking Time", value: "45–50 Seconds" },
      { label: "Operation Mode", value: "Touch Screen / IC Card" },
    ],
    safetySystem: [
      "Vehicle Guidance System",
      "Emergency Operation Mode",
      "Door Opening Direction Function",
      "Fault Indication",
      "Timeout Protection",
    ],
    applicationScenarios: [
      { label: "Vehicle Model", value: "Sedan and SUV" },
      { label: "Foundation", value: "C35 concrete embedded construction" },
      { label: "Application", value: "Commercial areas, office areas, small land areas" },
      { label: "Environment", value: "Indoor/Outdoor (canopy protection)" },
    ],
  },
  {
    id: "asp",
    model: "ASP",
    name: "Automated Shuttle Parking System",
    category: "automated",
    categoryLabel: "Fully Automated System",
    shortDescription: "Shuttle-based automated parking with turntable entry. Multiple designs for different garage layouts.",
    liftingCapacity: "2,350 KG",
    features: [
      "PLC Smart Control System",
      "Comprehensive Monitoring System",
      "Turntable Equipped at Entrance for Convenient Entry/Exit",
      "Multiple Designs to Match Different Parking Garage Layouts",
      "Fully Automated Parking Process for Best User Experience",
    ],
    specifications: [
      { label: "Model", value: "ASP" },
      { label: "Lifting Capacity", value: "2,350 KG" },
      { label: "Vehicle Dimension", value: "L5,200 × W1,950 × H2,050 mm" },
      { label: "Control System", value: "PLC Control" },
      { label: "Sliding Motor", value: "7.5/11 kW" },
      { label: "Lifting Motor", value: "2.2 kW" },
      { label: "Turning Motor", value: "2.2 kW" },
      { label: "Electrical Requirements", value: "Customizable" },
      { label: "Control Power", value: "24V" },
      { label: "Movement Speed", value: "30–50 m/min adjustable" },
      { label: "Operation Mode", value: "Touch Screen / IC Card" },
    ],
    safetySystem: [
      "Vehicle Guiding System",
      "Emergency Operative Mode",
      "Dual Emergency Power Supply",
      "Emergency Lighting",
      "Warning Device",
      "Power-off Braking System",
    ],
    applicationScenarios: [
      { label: "Vehicle Model", value: "Sedan and SUV" },
      { label: "Foundation", value: "C25 concrete embedded construction" },
      { label: "Application", value: "Commercial areas, office areas, small land areas, residential apartments" },
      { label: "Environment", value: "Indoor/Outdoor" },
    ],
  },
  {
    id: "ssp",
    model: "SSP",
    name: "Super Square Chess Parking System",
    category: "automated",
    categoryLabel: "Fully Automated System",
    shortDescription: "AI-powered chess-style parking robot. More spots in less space with faster retrieval.",
    liftingCapacity: "2,500 KG",
    features: [
      "More Parking Spots Needing Less Space",
      "Faster Than Planned Moving System",
      "No Worries to Find Parking",
      "Lower Space Requirement, Construction Costs and Power Support",
      "Easy Charging for New Energy Vehicles",
      "Flexible Requirements for Space Shape and Dimensions",
      "Imported High-Quality Components (Mitsubishi, Omron, Yaskawa, etc.)",
    ],
    specifications: [
      { label: "Model", value: "SSP" },
      { label: "Lifting Capacity", value: "2,500 KG" },
      { label: "Lifting Motor", value: "15 kW" },
      { label: "Drive Motor", value: "0.75 kW" },
      { label: "Drive Mode", value: "Gear Chain Shifting" },
      { label: "Movement Speed", value: "30 m/min" },
      { label: "Electrical Requirements", value: "Customizable: 3-Phase, 50/60 Hz" },
      { label: "Control Box", value: "PLC Control" },
      { label: "Monitoring System", value: "Security confirmation camera inside garage" },
      { label: "Operation Mode", value: "Touch Screen / IC Card" },
    ],
    safetySystem: [
      "Emergency Stop Button",
      "Up to 16 Pairs of Light Curtains",
      "Parking Position Detection",
      "Parking Guidance Positioning",
      "Personnel Error Detector",
      "Interlocked Associated Devices",
    ],
    applicationScenarios: [
      { label: "Vehicle Model", value: "Sedan and SUV" },
      { label: "Foundation", value: "C25 concrete embedded construction" },
      { label: "Application", value: "Commercial areas, office areas, small land areas, residential, shopping malls" },
      { label: "Environment", value: "Indoor/Outdoor" },
    ],
  },
  {
    id: "agv",
    model: "AGV",
    name: "Automated Guided Vehicle Parking",
    category: "automated",
    categoryLabel: "Fully Automated System",
    shortDescription: "AI-powered robotic parking with omni-directional robots. Highest parking efficiency available.",
    liftingCapacity: "2,700 KG",
    features: [
      "Highest Parking Efficiency",
      "Free-Roaming, Battery-Operated",
      "Automated Storage and Retrieval of Vehicles",
      "Omni-Directional Robots with Traffic Management Software",
      "In-House Design, Manufacturing, Installation & Service",
      "Intelligent Traffic Management Software",
      "Flexible Floor Plan Configuration",
      "24/7 Video Monitoring & Remote Access",
      "Suitable for Sedan, SUVs and Vans",
    ],
    specifications: [
      { label: "Model", value: "AGV" },
      { label: "Lifting Capacity", value: "2,700 KG" },
      { label: "Vehicle Dimension", value: "L5,300 × W1,950 × H1,350 mm" },
      { label: "Control Box", value: "Integrated Modules for Simple Wiring" },
      { label: "Drive Motor", value: "30 kW" },
      { label: "Electrical Requirements", value: "50/60 Hz" },
      { label: "Control Power", value: "24V" },
      { label: "Movement Speed", value: "30 m/min" },
      { label: "Operation Mode", value: "Mobile App / Key Fob / Remote Control" },
    ],
    safetySystem: [
      "Visual and Auditory Alarms",
      "Emergency Stops",
      "Vehicle Size and Positioning Sensors",
      "Collision Detectors and Laser Obstruction",
      "Emergency Operator Reset",
    ],
    applicationScenarios: [
      { label: "Vehicle Model", value: "Sedan, SUV, Van" },
      { label: "Foundation", value: "C55 concrete embedded construction" },
      { label: "Application", value: "Commercial areas, large parking facilities" },
      { label: "Environment", value: "Indoor" },
    ],
  },

  // ─── SPECIAL PLATFORMS ───
  {
    id: "s-vts",
    model: "S-VTS",
    name: "Scissor Vehicle Transport System",
    category: "special",
    categoryLabel: "Special Platform",
    shortDescription: "Hydraulic scissor platform for transporting vehicles and goods between floors.",
    liftingCapacity: "3,000 KG",
    features: [
      "Hydraulic Drive",
      "Four Cylinders EU Standard Design Available",
      "One to Three Platform(s) Customization",
      "100% Laser Cutting Process for All Parts",
      "Preassembled Parts for Easy Installation",
      "Effortless Disassembly and Relocation",
      "Press Button Operation Box",
      "Hydraulic Overload Protection",
      "Anti-Skid Platform",
      "Anti-Rust Smooth Powder Coating or Spray Painting",
      "Enhanced Anti-Corrosion Galvanized Platform",
      "Optional Remote Control and Fence (Safety Door)",
      "Customizable Colors",
      "12-Month Warranty (Extended Available)",
    ],
    specifications: [
      { label: "Model", value: "S-VTS" },
      { label: "Lifting Capacity", value: "3,000 KG" },
      { label: "Vehicle Height", value: "2,100 mm" },
      { label: "Vehicle Width", value: "2,000 mm" },
      { label: "Vehicle Length", value: "5,100 mm" },
      { label: "Control Box", value: "Relay Control" },
      { label: "Electrical Requirements", value: "Customizable" },
      { label: "Control Power", value: "24V" },
      { label: "Lifting Speed", value: "3.5 m/min" },
    ],
    safetySystem: ["Full Range Anti-Fall Lock", "Limit Switches", "Emergency Stop Button", "Explosion-Proof Valves"],
    applicationScenarios: [
      { label: "Application", value: "Vehicle Transport and Goods Elevating" },
      { label: "Foundation", value: "Based on project; Pit Depth > 500 mm" },
      { label: "Environment", value: "Indoor/Outdoor" },
    ],
  },
  {
    id: "f-vts",
    model: "F-VTS",
    name: "Four Post Vehicle Transport System",
    category: "special",
    categoryLabel: "Special Platform",
    shortDescription: "Four post platform for transporting vehicles and goods between floors in private buildings.",
    liftingCapacity: "≤ 2,000 KG",
    features: [
      "Transporting Goods or Vehicles Between Floors",
      "100% Laser Cutting Process for All Parts",
      "Preassembled Parts for Easy Installation",
      "Effortless Disassembly and Relocation",
      "Press Button Operation Box",
      "Hydraulic Overload Protection",
      "Anti-Skid Platform",
      "Anti-Rust Spray Painting",
      "Optional Remote Control and Ramp",
      "Customizable Colors",
      "12-Month Warranty (Extended Available)",
    ],
    specifications: [
      { label: "Model", value: "F-VTS" },
      { label: "Lifting Capacity", value: "≤ 2,000 KG" },
      { label: "Vehicle Height", value: "2,200 mm" },
      { label: "Vehicle Width", value: "2,500 mm" },
      { label: "Vehicle Length", value: "3,000 mm" },
      { label: "Vehicle Model", value: "Sedan, SUV, Pick-up Truck" },
      { label: "Control Box", value: "Integrated Modules for Simple Wiring" },
      { label: "Power Unit", value: "1.5 KW Hydraulic" },
      { label: "Control Power", value: "24V" },
      { label: "Lifting Speed", value: "4 m/min" },
    ],
    safetySystem: ["Dual Chain Anti-Fall Protection", "Limit Switches", "Emergency Stop Button", "Photocell Sensor", "Anti-Fall Locks"],
    applicationScenarios: [
      { label: "Buildings", value: "Private Villa or House" },
      { label: "Environment", value: "Indoor/Outdoor" },
    ],
  },
  {
    id: "ctt",
    model: "CTT",
    name: "Car Turntable",
    category: "special",
    categoryLabel: "Special Platform",
    shortDescription: "360-degree rotating turntable for vehicles. Low-profile design suitable for narrow spaces.",
    liftingCapacity: "3,000–10,000 KG",
    features: [
      "Simple Installation",
      "Servo Motors",
      "Low-profile Equipment Design",
      "Suitable for Narrow Space",
      "Safety and Reliability",
      "360 Degree Rotation",
      "Relay Control",
      "Customizable Plate Material and Rotating Speed",
      "Powder Coating Finishing",
      "Extremely Low Noise",
    ],
    specifications: [
      { label: "Model", value: "CTT" },
      { label: "Lifting Capacity", value: "3,000–10,000 KG" },
      { label: "Diameter of Table", value: "4.5–5.0 M" },
      { label: "Turning Speed", value: "2 circles/min" },
      { label: "Drive Mode", value: "Electric Motor" },
      { label: "Servo Motor", value: "4 × 120 W" },
      { label: "Control Box", value: "Integrated Modules for Simple Wiring" },
      { label: "Electrical Requirements", value: "Customizable: 1-Phase or 3-Phase, 50/60 Hz" },
      { label: "Operation Mode", value: "Button / Remote Control" },
    ],
    safetySystem: ["Emergency Stop Button"],
    applicationScenarios: [
      { label: "Vehicle Model", value: "Sedan / SUV" },
      { label: "Application", value: "Home Garage, Auto Exhibition, Car Display" },
      { label: "Environment", value: "Indoor/Outdoor (protection devices available)" },
    ],
  },
];

export const getProductsByCategory = (category: string) =>
  products.filter((p) => p.category === category);

export const getProductById = (id: string) =>
  products.find((p) => p.id === id);
