export interface ProductSpec {
  label: string;
  value: string;
}

export interface Product {
  id: string;
  model: string;
  name: string;
  category: "simple" | "semi-auto" | "automated";
  categoryLabel: string;
  shortDescription: string;
  liftingCapacity: string;
  features: string[];
  specifications: ProductSpec[];
  safetySystem: string[];
  applicationScenarios: ProductSpec[];
}

export const productCategories = [
  {
    id: "simple",
    title: "Simple Parking Lifts",
    description: "Space-saving and durable parking solutions at low cost. Hydraulic-driven, easy to install and relocate.",
    imageKey: "simple" as const,
  },
  {
    id: "semi-auto",
    title: "Semi-Auto Parking Systems",
    description: "Intelligent semi-automated parking systems with smart controls. Ideal for residential and commercial spaces.",
    imageKey: "semi-auto" as const,
  },
  {
    id: "automated",
    title: "Fully Automated Systems",
    description: "High-tech fully automated parking towers and rotary systems for maximum space efficiency.",
    imageKey: "automated" as const,
  },
];

export const products: Product[] = [
  {
    id: "tp-320",
    model: "TP-320",
    name: "Four Post Car Parking Lift",
    category: "simple",
    categoryLabel: "Simple Parking Lift",
    shortDescription: "Heavy-duty four post hydraulic lift with 3,200 KG capacity. Ideal for sedans and SUVs.",
    liftingCapacity: "3,200 KG",
    features: [
      "Double Hydraulic Lifting Cylinders Direct Drive",
      "Multiple Parking Heights",
      "100% Laser Cutting Process for All Parts",
      "Preassembled Parts for Easy Installation",
      "Effortless Disassembly and Relocation",
      "Safety Key Switch Controller",
      "Hydraulic Overload Protection",
      "Anti-Skid Ramp and Platform",
      "Anti-Rust Smooth Powder Coating Finishing",
      "Enhanced Anti-Corrosion Galvanized Waving Plates",
      "Tire Protection Plates",
      "IP65 Electrical Devices for Outdoor Use",
      "12-Month Warranty (Extended Available)",
      "Customizable Colors",
      "Optional Remote Control",
      "Posts Can Be Shared for Multiple Parallel Lifts",
    ],
    specifications: [
      { label: "Model", value: "TP-320" },
      { label: "Lifting Capacity", value: "3,200 KG" },
      { label: "Vehicle Height", value: "1,550–2,050 mm" },
      { label: "Vehicle Width", value: "≤ 2,200 mm" },
      { label: "Vehicle Length", value: "5,000 mm" },
      { label: "Control Box", value: "Integrated Modules for Simple Wiring" },
      { label: "Power Unit", value: "3.0 KW Hydraulic" },
      { label: "Electrical Requirements", value: "Customizable: 3-Phase, 50/60 Hz" },
      { label: "Control Power", value: "24V" },
      { label: "Parking Time", value: "45–55 Seconds" },
    ],
    safetySystem: [
      "17 Full Range Anti-Fall Locks",
      "Limit Switches",
      "Emergency Stop Button",
    ],
    applicationScenarios: [
      { label: "Vehicle Model", value: "Sedan, Regular SUV" },
      { label: "Foundation", value: "C25–C30; thickness: 300 mm" },
      { label: "Ceiling Height", value: "3,900 mm (Sedan+SUV) / 4,300 mm (2 SUVs)" },
      { label: "Environment", value: "Indoor/Outdoor (protection devices available)" },
    ],
  },
  {
    id: "tp-270",
    model: "TP-270",
    name: "Two Post Car Parking Lift",
    category: "simple",
    categoryLabel: "Simple Parking Lift",
    shortDescription: "Versatile two post lift with 2,700 KG capacity. Supports 1-phase or 3-phase power.",
    liftingCapacity: "2,700 KG",
    features: [
      "Double Hydraulic Lifting Cylinders Direct Drive",
      "Multiple Parking Heights",
      "100% Laser Cutting Process for All Parts",
      "Preassembled Parts for Easy Installation",
      "Effortless Disassembly and Relocation",
      "Safety Key Switch Controller",
      "Hydraulic Overload Protection",
      "Anti-Skid Ramp and Platform",
      "Anti-Rust Smooth Powder Coating Finishing",
      "Enhanced Anti-Corrosion Galvanized Waving Plates",
      "Optional Remote Control",
      "Customizable Colors",
      "12-Month Warranty (Extended Available)",
      "Posts Can Be Shared for Multiple Parallel Lifts",
    ],
    specifications: [
      { label: "Model", value: "TP-270" },
      { label: "Lifting Capacity", value: "2,700 KG" },
      { label: "Vehicle Height", value: "1,550–2,050 mm" },
      { label: "Vehicle Width", value: "2,200 mm" },
      { label: "Vehicle Length", value: "5,000 mm" },
      { label: "Control Box", value: "Integrated Modules for Simple Wiring" },
      { label: "Power Unit", value: "2.2 KW Hydraulic" },
      { label: "Electrical Requirements", value: "Customizable: 1-Phase or 3-Phase" },
      { label: "Control Power", value: "24V" },
      { label: "Parking Time", value: "45–55 Seconds" },
    ],
    safetySystem: [
      "17 Full Range Anti-Fall Locks",
      "Limit Switches",
      "Emergency Stop Button",
      "Photocell Sensor",
      "Lock Down Button",
    ],
    applicationScenarios: [
      { label: "Vehicle Model", value: "Sedan, Regular SUV" },
      { label: "Foundation", value: "C25–C30; thickness: 300 mm" },
      { label: "Ceiling Height", value: "3,900 mm (Sedan+SUV) / 4,300 mm (2 SUVs)" },
      { label: "Buildings", value: "Private Garage, Residential, Shopping Mall, Car Dealership" },
      { label: "Environment", value: "Indoor/Outdoor (protection devices available)" },
    ],
  },
  {
    id: "ips",
    model: "IPS-2/3/4",
    name: "In-ground Parking System",
    category: "semi-auto",
    categoryLabel: "Semi-Auto Parking System",
    shortDescription: "Underground parking system that hides vehicles below ground level. Perfect for private villas.",
    liftingCapacity: "2,000–2,500 KG",
    features: [
      "Hydraulic Driven with Precise Control",
      "Vehicles Hidden Underground When Parked",
      "100% Laser Cutting Process for All Parts",
      "Preassembled Parts for Easy Installation",
      "Safety Key Switch Controller",
      "Hydraulic Overload Protection",
      "Anti-Skid Platform",
      "Galvanized Waving Plates with Powder Coating",
      "Customizable Colors",
      "12-Month Warranty (Extended Available)",
    ],
    specifications: [
      { label: "Model", value: "IPS-2/3/4" },
      { label: "Lifting Capacity", value: "2,000–2,500 KG" },
      { label: "Vehicle Height", value: "1,550–2,050 mm" },
      { label: "Vehicle Width", value: "≤ 2,050 mm" },
      { label: "Vehicle Length", value: "5,000 mm" },
      { label: "Control Box", value: "PLC Control" },
      { label: "Power Unit", value: "5.5 KW Hydraulic" },
      { label: "Electrical Requirements", value: "Customizable: 3-Phase, 50/60 Hz" },
      { label: "Control Power", value: "24V" },
      { label: "Lifting Speed", value: "3.6–8.0 m/min" },
    ],
    safetySystem: [
      "Full Range Anti-Fall Locks",
      "Limit Switches",
      "Emergency Stop Button",
      "Photocell Sensors",
    ],
    applicationScenarios: [
      { label: "Vehicle Model", value: "Sedan (SUV customizable)" },
      { label: "Pit Depth", value: "2,430 mm" },
      { label: "Buildings", value: "Private Villa, Apartment" },
      { label: "Environment", value: "Indoor/Outdoor (protection devices available)" },
    ],
  },
  {
    id: "pps",
    model: "PPS-2~PPS-6",
    name: "Lift-Sliding Puzzle Parking System",
    category: "semi-auto",
    categoryLabel: "Semi-Auto Parking System",
    shortDescription: "Multi-level puzzle parking with lift and slide mechanism. Maximizes parking capacity.",
    liftingCapacity: "2,000–2,500 KG",
    features: [
      "Motor or Hydraulic Driven",
      "Intelligent Smart Parking System",
      "100% Laser Cutting Process for All Parts",
      "Swiping IC Card / Press Button Operation",
      "Hydraulic Overload Protection",
      "Anti-Skid Ramp and Platform",
      "Galvanized Waving Plates or Powder Coating",
      "Customizable Colors and Level Numbers",
      "Free-Access Parking Platform",
      "Schneider PLC Controller",
      "Low Noise Operation",
      "12-Month Warranty (Extended Available)",
    ],
    specifications: [
      { label: "Model", value: "PPS-2 ~ PPS-6" },
      { label: "Lifting Capacity", value: "2,000–2,500 KG (on floor)" },
      { label: "Vehicle Height", value: "1,550–2,050 mm" },
      { label: "Vehicle Width", value: "2,050 mm" },
      { label: "Vehicle Length", value: "< 5,300 mm" },
      { label: "Control Box", value: "PLC Control" },
      { label: "Sliding Motor", value: "0.2/0.4 kW" },
      { label: "Lifting Motor", value: "22–37 kW" },
      { label: "Lifting Speed", value: "4–6 m/min" },
      { label: "Sliding Speed", value: "6–8 m/min" },
      { label: "Operation Mode", value: "Button with IC Card" },
    ],
    safetySystem: [
      "Anti-Fall Hooks",
      "Limit Switches",
      "Emergency Stop Button",
      "Photocell Sensors",
      "Anti-Loose Device",
      "Stop Rod for Tire Protection",
      "Optional Safety Gate on Ground Floor",
    ],
    applicationScenarios: [
      { label: "Vehicle Model", value: "Sedan / SUV" },
      { label: "Ceiling Height", value: "Customizable" },
      { label: "Buildings", value: "Residential Community, Shopping Mall, Office Building" },
      { label: "Environment", value: "Indoor/Outdoor" },
    ],
  },
  {
    id: "rps",
    model: "RPS",
    name: "Rotary Parking System",
    category: "automated",
    categoryLabel: "Fully Automated System",
    shortDescription: "Eye-catching rotary design parking 8–20 vehicles in minimal footprint. Fully automated.",
    liftingCapacity: "2,000–2,500 KG",
    features: [
      "Minimum 8, Maximum 20 Parking Spaces",
      "Eye-Catching Innovative Design",
      "100% Laser Cutting Process for All Parts",
      "Preassembled Parts for Easy Installation",
      "IC Card / Touch Screen Operation",
      "Anti-Skid Ramp and Platform",
      "Anti-Rust Smooth Powder Coating",
      "Customizable Colors",
      "Fully Automated Operation",
      "Extremely Low Noise",
      "Low Electrical Power Consumption",
      "Motor: SEW or Nord",
      "Easy Maintenance",
      "12-Month Warranty (Extended Available)",
    ],
    specifications: [
      { label: "Model", value: "RPS" },
      { label: "Lifting Capacity", value: "2,000–2,500 KG" },
      { label: "Vehicle Height", value: "1,550–2,050 mm" },
      { label: "Vehicle Width", value: "1,900 mm" },
      { label: "Vehicle Length", value: "≤ 5,300 mm" },
      { label: "Control Box", value: "PLC Control" },
      { label: "Power Unit", value: "9.2 kW × 2" },
      { label: "Electrical Requirements", value: "Customizable: 3-Phase, 50/60 Hz" },
      { label: "Control Power", value: "24V" },
      { label: "Lifting Speed", value: "4–6 m/min" },
    ],
    safetySystem: [
      "Limit Switches",
      "Emergency Stop Button",
      "Photocell Sensors",
      "Mechanical Interlock",
    ],
    applicationScenarios: [
      { label: "Vehicle Model", value: "Sedan / SUV" },
      { label: "Ceiling Height", value: "Customizable" },
      { label: "Site", value: "Limited Parking Area" },
      { label: "Environment", value: "Indoor/Outdoor (protection devices available)" },
    ],
  },
  {
    id: "atp",
    model: "ATP",
    name: "Automated Tower Parking System",
    category: "automated",
    categoryLabel: "Fully Automated System",
    shortDescription: "The most cost-effective fully automated parking tower. Maximum space utilization with smart PLC control.",
    liftingCapacity: "2,000 KG",
    features: [
      "Advanced PLC Control System (Schneider)",
      "Smooth Operation and High Efficiency",
      "Human-Machine Computer Integrated Management",
      "Maximized Space Utilization",
      "Fully Automated Parking Process",
      "Easy Operation and Maintenance",
      "Customizable Appearance",
      "SEW Brand Motor for Strong Power",
      "Energy Saving",
      "Low Noise",
      "Oil Drip Tray Platform",
      "Vehicle Guidance System",
    ],
    specifications: [
      { label: "Model", value: "ATP" },
      { label: "Lifting Capacity", value: "2,000 KG (max 2,050 KG)" },
      { label: "Vehicle Dimension", value: "L5,200 × W2,050 × H2,050 mm" },
      { label: "Control Box", value: "PLC Control" },
      { label: "Sliding Motor", value: "1.5/11 kW" },
      { label: "Lifting Motor", value: "0.2/2.2/3.7 kW" },
      { label: "Electrical Requirements", value: "Customizable: 3-Phase, 50/60 Hz" },
      { label: "Control Power", value: "240V" },
      { label: "Parking Time", value: "45–50 Seconds" },
      { label: "Operation Mode", value: "Touch Screen / IC Card" },
    ],
    safetySystem: [
      "Vehicle Guidance System",
      "Emergency Operation Mode",
      "Door Opening Direction Function",
      "Fault Indication",
      "Timeout Protection",
    ],
    applicationScenarios: [
      { label: "Vehicle Model", value: "Sedan and SUV" },
      { label: "Foundation", value: "C35 concrete embedded construction" },
      { label: "Application", value: "Commercial areas, office areas, small land areas" },
      { label: "Environment", value: "Indoor/Outdoor (canopy protection)" },
    ],
  },
];

export const getProductsByCategory = (category: string) =>
  products.filter((p) => p.category === category);

export const getProductById = (id: string) =>
  products.find((p) => p.id === id);
